apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  # Shared data using an emptyDir volume
  volumes:
  - name: shared-data
    emptyDir: {}

  # Main application Container
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  # Sidecar container
  # Observing restarts:
  #       command: ["sh", "-c", "exit 1"]
  - name: sidecar
    image: busybox
    command: ["sh", "-c", "while true; do date >> /data/index.html; sleep 5; done"] 
    volumeMounts:
    - name: shared-data
      mountPath: /data