apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  # shared storage
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    # main app
    - name: app
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    # sidecar
    - name: sidecar
      image: busybox
      command:
        ["sh", "-c", "while true; do date >> /data/index.html; sleep 5; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
