apiVersion: v1
kind: Service
metadata:
  name: service-selector-demo-service
  namespace: dev
spec:
  selector:
    app: service-selector-demo # must match deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
