apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-secret-deployment
  template:
    metadata:
      labels:
        app: config-secret-deployment
    spec:
      containers:
      - name: app
        image: nginx:1.27
        ports:
        - containerPort: 80
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: stateless-app-config
              key: ENV
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: stateless-app-secret
              key: PASSWORD
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: stateless-app-config
      - name: secret-volume
        secret:
          secretName: stateless-app-secret