apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-demo
  template:
    metadata:
      labels:
        app: resource-demo
    spec:
      containers:
        - name: app
          image: nginx
          # Triggers OOMKilled: keeps adding a's, so the variable 'x' uses more RAM
          # command: ["/bin/sh", "-c", "x='a'; while true; do x=$x$x; done"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
