apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

        - key: "dedicated"
          operator: "Equal"
          value: "experimental"
          effect: "NoSchedule"

        - key: "test"
          operator: "Equal"
          value: "noschedule"
          effect: "NoSchedule"

      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
