apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-limit-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-limit-demo
  template:
    metadata:
      labels:
        app: no-limit-demo
    spec:
      containers:
        - name: app
          image: nginx
