apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-demo-no-limits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-demo-no-limits
  template:
    metadata:
      labels:
        app: resource-demo-no-limits
    spec:
      containers:
      - name: app
        image: nginx