apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-pull-loop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-pull-loop-demo
  template:
    metadata:
      labels:
        app: image-pull-loop-demo
    spec:
      containers:
        - name: app
          image: fakeimage
