apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: hashicorp/http-echo
      args:
        - "-text=this is the backend"
        - "-listen=:8080"
      ports:
        - containerPort: 8080