apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: curlimages/curl:latest
      command: ["sleep", "3600"]