apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: curlimages/curl
      command: ["sleep", "3600"]  # Keep the pod running
      ports:
        - containerPort: 8080