apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: dev
spec:
  containers:
    - name: exploit-container
      image: nginx:1.27
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /host-data
          name: host-vol
  volumes:
    - name: host-vol
      hostPath:
        path: /etc
