apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  project: default
  source:
    repoURL: https://github.com/Demarcus11/k8s-enterprise-capstone-team1.git
    targetRevision: week09-10-Joseph
    path: week09-10\manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  #auto sync enabled
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
