apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-demo
  namespace: dev
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret